/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 5.0.12
 * Contact: ergoplatform@protonmail.com
 * Generated by: https://openapi-generator.tech
 */

/// AddressValidity : Validity status of Ergo address



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AddressValidity {
    /// Encoded Ergo Address
    #[serde(rename = "address")]
    pub address: String,
    #[serde(rename = "isValid")]
    pub is_valid: bool,
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

impl AddressValidity {
    /// Validity status of Ergo address
    pub fn new(address: String, is_valid: bool) -> AddressValidity {
        AddressValidity {
            address,
            is_valid,
            error: None,
        }
    }
}


