/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 5.0.12
 * Contact: ergoplatform@protonmail.com
 * Generated by: https://openapi-generator.tech
 */

/// BalancesSnapshot : Amount of Ergo tokens and assets



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BalancesSnapshot {
    #[serde(rename = "height")]
    pub height: i32,
    #[serde(rename = "balance")]
    pub balance: i64,
    #[serde(rename = "assets", skip_serializing_if = "Option::is_none")]
    pub assets: Option<Vec<crate::models::Asset>>,
}

impl BalancesSnapshot {
    /// Amount of Ergo tokens and assets
    pub fn new(height: i32, balance: i64) -> BalancesSnapshot {
        BalancesSnapshot {
            height,
            balance,
            assets: None,
        }
    }
}


