/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 5.0.12
 * Contact: ergoplatform@protonmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BlockAdProofs {
    /// Base16-encoded 32 byte modifier id
    #[serde(rename = "headerId")]
    pub header_id: String,
    /// Base16-encoded ad proofs
    #[serde(rename = "proofBytes")]
    pub proof_bytes: String,
    /// Base16-encoded 32 byte digest
    #[serde(rename = "digest")]
    pub digest: String,
    /// Size in bytes
    #[serde(rename = "size")]
    pub size: i32,
}

impl BlockAdProofs {
    pub fn new(header_id: String, proof_bytes: String, digest: String, size: i32) -> BlockAdProofs {
        BlockAdProofs {
            header_id,
            proof_bytes,
            digest,
            size,
        }
    }
}


