/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 5.0.12
 * Contact: ergoplatform@protonmail.com
 * Generated by: https://openapi-generator.tech
 */

/// BoxesRequestHolderTargetAssetsInnerInner : TokenId or Long



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BoxesRequestHolderTargetAssetsInnerInner {
}

impl BoxesRequestHolderTargetAssetsInnerInner {
    /// TokenId or Long
    pub fn new() -> BoxesRequestHolderTargetAssetsInnerInner {
        BoxesRequestHolderTargetAssetsInnerInner {
        }
    }
}


