/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 5.0.12
 * Contact: ergoplatform@protonmail.com
 * Generated by: https://openapi-generator.tech
 */

/// CandidateBlock : Can be null if node is not mining or candidate block is not ready



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CandidateBlock {
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<i32>,
    /// Base16-encoded 32 byte digest
    #[serde(rename = "extensionHash")]
    pub extension_hash: String,
    /// Basic timestamp definition
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<i64>,
    /// Base16-encoded 33 byte digest - digest with extra byte with tree height
    #[serde(rename = "stateRoot", skip_serializing_if = "Option::is_none")]
    pub state_root: Option<String>,
    #[serde(rename = "nBits", skip_serializing_if = "Option::is_none")]
    pub n_bits: Option<i64>,
    /// Base16-encoded ad proofs
    #[serde(rename = "adProofBytes", skip_serializing_if = "Option::is_none")]
    pub ad_proof_bytes: Option<String>,
    /// Base16-encoded 32 byte modifier id
    #[serde(rename = "parentId")]
    pub parent_id: String,
    #[serde(rename = "transactionsNumber", skip_serializing_if = "Option::is_none")]
    pub transactions_number: Option<i32>,
    /// Ergo transaction objects
    #[serde(rename = "transactions", skip_serializing_if = "Option::is_none")]
    pub transactions: Option<Vec<crate::models::ErgoTransaction>>,
    /// Base16-encoded votes for a soft-fork and parameters
    #[serde(rename = "votes", skip_serializing_if = "Option::is_none")]
    pub votes: Option<String>,
}

impl CandidateBlock {
    /// Can be null if node is not mining or candidate block is not ready
    pub fn new(extension_hash: String, parent_id: String) -> CandidateBlock {
        CandidateBlock {
            version: None,
            extension_hash,
            timestamp: None,
            state_root: None,
            n_bits: None,
            ad_proof_bytes: None,
            parent_id,
            transactions_number: None,
            transactions: None,
            votes: None,
        }
    }
}


