/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 5.0.12
 * Contact: ergoplatform@protonmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ContainsAssetPredicateAllOf {
    #[serde(rename = "assetId", skip_serializing_if = "Option::is_none")]
    pub asset_id: Option<String>,
}

impl ContainsAssetPredicateAllOf {
    pub fn new() -> ContainsAssetPredicateAllOf {
        ContainsAssetPredicateAllOf {
            asset_id: None,
        }
    }
}


