/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 5.0.12
 * Contact: ergoplatform@protonmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ContainsPredicate {
    #[serde(rename = "predicate")]
    pub predicate: String,
    #[serde(rename = "register", skip_serializing_if = "Option::is_none")]
    pub register: Option<String>,
    #[serde(rename = "bytes", skip_serializing_if = "Option::is_none")]
    pub bytes: Option<String>,
}

impl ContainsPredicate {
    pub fn new(predicate: String) -> ContainsPredicate {
        ContainsPredicate {
            predicate,
            register: None,
            bytes: None,
        }
    }
}


