/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 5.0.12
 * Contact: ergoplatform@protonmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DeriveKey {
    /// Derivation path for a new secret to derive
    #[serde(rename = "derivationPath")]
    pub derivation_path: String,
}

impl DeriveKey {
    pub fn new(derivation_path: String) -> DeriveKey {
        DeriveKey {
            derivation_path,
        }
    }
}


