/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 5.0.12
 * Contact: ergoplatform@protonmail.com
 * Generated by: https://openapi-generator.tech
 */

/// DlogCommitment : Randomness and commitment for the first step of the Schnorr protocol



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DlogCommitment {
    /// Hex-encoded big-endian 256-bits secret exponent
    #[serde(rename = "r")]
    pub r: String,
    /// Hex-encoded \"g\" generator for the Diffie-Hellman tuple (secp256k1 curve point)
    #[serde(rename = "a")]
    pub a: String,
}

impl DlogCommitment {
    /// Randomness and commitment for the first step of the Schnorr protocol
    pub fn new(r: String, a: String) -> DlogCommitment {
        DlogCommitment {
            r,
            a,
        }
    }
}


