/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 5.0.12
 * Contact: ergoplatform@protonmail.com
 * Generated by: https://openapi-generator.tech
 */

/// EmissionInfo : Emission info for height



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EmissionInfo {
    #[serde(rename = "minerReward", skip_serializing_if = "Option::is_none")]
    pub miner_reward: Option<i64>,
    #[serde(rename = "totalCoinsIssued", skip_serializing_if = "Option::is_none")]
    pub total_coins_issued: Option<i64>,
    #[serde(rename = "totalRemainCoins", skip_serializing_if = "Option::is_none")]
    pub total_remain_coins: Option<i64>,
    #[serde(rename = "reemitted", skip_serializing_if = "Option::is_none")]
    pub reemitted: Option<i64>,
}

impl EmissionInfo {
    /// Emission info for height
    pub fn new() -> EmissionInfo {
        EmissionInfo {
            miner_reward: None,
            total_coins_issued: None,
            total_remain_coins: None,
            reemitted: None,
        }
    }
}


