/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 5.0.12
 * Contact: ergoplatform@protonmail.com
 * Generated by: https://openapi-generator.tech
 */

/// EmissionScripts : Emission related scripts



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EmissionScripts {
    #[serde(rename = "emission", skip_serializing_if = "Option::is_none")]
    pub emission: Option<String>,
    #[serde(rename = "reemission", skip_serializing_if = "Option::is_none")]
    pub reemission: Option<String>,
    #[serde(rename = "pay2Reemission", skip_serializing_if = "Option::is_none")]
    pub pay2_reemission: Option<String>,
}

impl EmissionScripts {
    /// Emission related scripts
    pub fn new() -> EmissionScripts {
        EmissionScripts {
            emission: None,
            reemission: None,
            pay2_reemission: None,
        }
    }
}


