/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 5.0.12
 * Contact: ergoplatform@protonmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ErgoTransactionUnsignedInput {
    /// Base16-encoded transaction box id bytes. Should be 32 bytes long
    #[serde(rename = "boxId")]
    pub box_id: String,
    #[serde(rename = "extension", skip_serializing_if = "Option::is_none")]
    pub extension: Option<::std::collections::HashMap<String, String>>,
}

impl ErgoTransactionUnsignedInput {
    pub fn new(box_id: String) -> ErgoTransactionUnsignedInput {
        ErgoTransactionUnsignedInput {
            box_id,
            extension: None,
        }
    }
}


