/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 5.0.12
 * Contact: ergoplatform@protonmail.com
 * Generated by: https://openapi-generator.tech
 */

/// ErgoTransaction : Ergo transaction



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ErgoTransaction {
    /// Base16-encoded transaction id bytes
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Inputs of the transaction
    #[serde(rename = "inputs")]
    pub inputs: Vec<crate::models::ErgoTransactionInput>,
    /// Data inputs of the transaction
    #[serde(rename = "dataInputs")]
    pub data_inputs: Vec<crate::models::ErgoTransactionDataInput>,
    /// Outputs of the transaction
    #[serde(rename = "outputs")]
    pub outputs: Vec<crate::models::ErgoTransactionOutput>,
    /// Size in bytes
    #[serde(rename = "size", skip_serializing_if = "Option::is_none")]
    pub size: Option<i32>,
}

impl ErgoTransaction {
    /// Ergo transaction
    pub fn new(inputs: Vec<crate::models::ErgoTransactionInput>, data_inputs: Vec<crate::models::ErgoTransactionDataInput>, outputs: Vec<crate::models::ErgoTransactionOutput>) -> ErgoTransaction {
        ErgoTransaction {
            id: None,
            inputs,
            data_inputs,
            outputs,
            size: None,
        }
    }
}


