/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 5.0.12
 * Contact: ergoplatform@protonmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ErgoTransactionInput {
    /// Base16-encoded transaction box id bytes. Should be 32 bytes long
    #[serde(rename = "boxId")]
    pub box_id: String,
    #[serde(rename = "spendingProof")]
    pub spending_proof: Box<crate::models::SpendingProof>,
}

impl ErgoTransactionInput {
    pub fn new(box_id: String, spending_proof: crate::models::SpendingProof) -> ErgoTransactionInput {
        ErgoTransactionInput {
            box_id,
            spending_proof: Box::new(spending_proof),
        }
    }
}


