/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 5.0.12
 * Contact: ergoplatform@protonmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Extension {
    /// Base16-encoded 32 byte modifier id
    #[serde(rename = "headerId")]
    pub header_id: String,
    /// Base16-encoded 32 byte digest
    #[serde(rename = "digest")]
    pub digest: String,
    /// List of key-value records
    #[serde(rename = "fields", deserialize_with = "Option::deserialize")]
    pub fields: Option<Vec<Vec<String>>>,
}

impl Extension {
    pub fn new(header_id: String, digest: String, fields: Option<Vec<Vec<String>>>) -> Extension {
        Extension {
            header_id,
            digest,
            fields,
        }
    }
}


