/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 5.0.12
 * Contact: ergoplatform@protonmail.com
 * Generated by: https://openapi-generator.tech
 */

/// FeeHistogramBin : Fee histogram bin



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FeeHistogramBin {
    #[serde(rename = "nTxns", skip_serializing_if = "Option::is_none")]
    pub n_txns: Option<i32>,
    #[serde(rename = "totalFee", skip_serializing_if = "Option::is_none")]
    pub total_fee: Option<i64>,
}

impl FeeHistogramBin {
    /// Fee histogram bin
    pub fn new() -> FeeHistogramBin {
        FeeHistogramBin {
            n_txns: None,
            total_fee: None,
        }
    }
}


