/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 5.0.12
 * Contact: ergoplatform@protonmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetIndexedHeight200Response {
    /// number of blocks indexed
    #[serde(rename = "indexedHeight", skip_serializing_if = "Option::is_none")]
    pub indexed_height: Option<i32>,
    /// number of all known blocks
    #[serde(rename = "fullHeight", skip_serializing_if = "Option::is_none")]
    pub full_height: Option<i32>,
}

impl GetIndexedHeight200Response {
    pub fn new() -> GetIndexedHeight200Response {
        GetIndexedHeight200Response {
            indexed_height: None,
            full_height: None,
        }
    }
}


