/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 5.0.12
 * Contact: ergoplatform@protonmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetTxsByAddress200Response {
    /// Array of transactions
    #[serde(rename = "items", skip_serializing_if = "Option::is_none")]
    pub items: Option<Vec<crate::models::IndexedErgoTransaction>>,
    /// Total count of retreived transactions
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<i32>,
}

impl GetTxsByAddress200Response {
    pub fn new() -> GetTxsByAddress200Response {
        GetTxsByAddress200Response {
            items: None,
            total: None,
        }
    }
}


