/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 5.0.12
 * Contact: ergoplatform@protonmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PeersStatus {
    /// Basic timestamp definition
    #[serde(rename = "lastIncomingMessage")]
    pub last_incoming_message: i64,
    /// Basic timestamp definition
    #[serde(rename = "currentNetworkTime")]
    pub current_network_time: i64,
}

impl PeersStatus {
    pub fn new(last_incoming_message: i64, current_network_time: i64) -> PeersStatus {
        PeersStatus {
            last_incoming_message,
            current_network_time,
        }
    }
}


