/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 5.0.12
 * Contact: ergoplatform@protonmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PopowHeader {
    #[serde(rename = "header")]
    pub header: Box<crate::models::BlockHeader>,
    /// Array of header interlinks
    #[serde(rename = "interlinks")]
    pub interlinks: Vec<String>,
}

impl PopowHeader {
    pub fn new(header: crate::models::BlockHeader, interlinks: Vec<String>) -> PopowHeader {
        PopowHeader {
            header: Box::new(header),
            interlinks,
        }
    }
}


