/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 5.0.12
 * Contact: ergoplatform@protonmail.com
 * Generated by: https://openapi-generator.tech
 */

/// PowSolutions : An object containing all components of pow solution



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PowSolutions {
    /// Base16-encoded public key
    #[serde(rename = "pk")]
    pub pk: String,
    #[serde(rename = "w")]
    pub w: String,
    #[serde(rename = "n")]
    pub n: String,
    #[serde(rename = "d")]
    pub d: f32,
}

impl PowSolutions {
    /// An object containing all components of pow solution
    pub fn new(pk: String, w: String, n: String, d: f32) -> PowSolutions {
        PowSolutions {
            pk,
            w,
            n,
            d,
        }
    }
}


