/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 5.0.12
 * Contact: ergoplatform@protonmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RewardAddress {
    /// Encoded Ergo Address
    #[serde(rename = "rewardAddress")]
    pub reward_address: String,
}

impl RewardAddress {
    pub fn new(reward_address: String) -> RewardAddress {
        RewardAddress {
            reward_address,
        }
    }
}


