/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 5.0.12
 * Contact: ergoplatform@protonmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RewardPubKey {
    #[serde(rename = "rewardPubkey")]
    pub reward_pubkey: String,
}

impl RewardPubKey {
    pub fn new(reward_pubkey: String) -> RewardPubKey {
        RewardPubKey {
            reward_pubkey,
        }
    }
}


