/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 5.0.12
 * Contact: ergoplatform@protonmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ScanIdBoxId {
    #[serde(rename = "scanId")]
    pub scan_id: i32,
    /// Base16-encoded transaction box id bytes. Should be 32 bytes long
    #[serde(rename = "boxId")]
    pub box_id: String,
}

impl ScanIdBoxId {
    pub fn new(scan_id: i32, box_id: String) -> ScanIdBoxId {
        ScanIdBoxId {
            scan_id,
            box_id,
        }
    }
}


