/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 5.0.12
 * Contact: ergoplatform@protonmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ScriptBytes {
    /// Base16-encoded bytes
    #[serde(rename = "bytes")]
    pub bytes: String,
}

impl ScriptBytes {
    pub fn new(bytes: String) -> ScriptBytes {
        ScriptBytes {
            bytes,
        }
    }
}


