/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 5.0.12
 * Contact: ergoplatform@protonmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SnapshotsInfo {
    /// Map of available manifests height -> manifestId
    #[serde(rename = "availableManifests")]
    pub available_manifests: Vec<serde_json::Value>,
}

impl SnapshotsInfo {
    pub fn new(available_manifests: Vec<serde_json::Value>) -> SnapshotsInfo {
        SnapshotsInfo {
            available_manifests,
        }
    }
}


