/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 5.0.12
 * Contact: ergoplatform@protonmail.com
 * Generated by: https://openapi-generator.tech
 */

/// SpendingProof : Spending proof for transaction input



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SpendingProof {
    /// Base16-encoded spending proofs
    #[serde(rename = "proofBytes")]
    pub proof_bytes: String,
    /// Variables to be put into context
    #[serde(rename = "extension")]
    pub extension: ::std::collections::HashMap<String, String>,
}

impl SpendingProof {
    /// Spending proof for transaction input
    pub fn new(proof_bytes: String, extension: ::std::collections::HashMap<String, String>) -> SpendingProof {
        SpendingProof {
            proof_bytes,
            extension,
        }
    }
}


