/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 5.0.12
 * Contact: ergoplatform@protonmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SyncInfo {
    #[serde(rename = "address")]
    pub address: String,
    #[serde(rename = "mode")]
    pub mode: crate::models::PeerMode,
    #[serde(rename = "version")]
    pub version: String,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "height")]
    pub height: i32,
}

impl SyncInfo {
    pub fn new(address: String, mode: crate::models::PeerMode, version: String, status: String, height: i32) -> SyncInfo {
        SyncInfo {
            address,
            mode,
            version,
            status,
            height,
        }
    }
}


