/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 5.0.12
 * Contact: ergoplatform@protonmail.com
 * Generated by: https://openapi-generator.tech
 */

/// TransactionSigningRequestSecrets : Secrets used for signing



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TransactionSigningRequestSecrets {
    /// Sequence of secret exponents (DLOG secrets)
    #[serde(rename = "dlog", skip_serializing_if = "Option::is_none")]
    pub dlog: Option<Vec<String>>,
    /// Sequence of secret Diffie-Hellman tuple exponents (DHT secrets)
    #[serde(rename = "dht", skip_serializing_if = "Option::is_none")]
    pub dht: Option<Vec<crate::models::DhtSecret>>,
}

impl TransactionSigningRequestSecrets {
    /// Secrets used for signing
    pub fn new() -> TransactionSigningRequestSecrets {
        TransactionSigningRequestSecrets {
            dlog: None,
            dht: None,
        }
    }
}


