/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 5.0.12
 * Contact: ergoplatform@protonmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UnlockWallet {
    /// Password to decrypt wallet file with
    #[serde(rename = "pass")]
    pub pass: String,
}

impl UnlockWallet {
    pub fn new(pass: String) -> UnlockWallet {
        UnlockWallet {
            pass,
        }
    }
}


