/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 5.0.12
 * Contact: ergoplatform@protonmail.com
 * Generated by: https://openapi-generator.tech
 */

/// WorkMessage : Block candidate related data for external miner to perform work



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct WorkMessage {
    /// Base16-encoded block header bytes without PoW solution
    #[serde(rename = "msg")]
    pub msg: String,
    /// Work target value
    #[serde(rename = "b")]
    pub b: i32,
    /// Base16-encoded miner public key
    #[serde(rename = "pk")]
    pub pk: String,
    #[serde(rename = "proof", skip_serializing_if = "Option::is_none")]
    pub proof: Option<crate::models::ProofOfUpcomingTransactions>,
}

impl WorkMessage {
    /// Block candidate related data for external miner to perform work
    pub fn new(msg: String, b: i32, pk: String) -> WorkMessage {
        WorkMessage {
            msg,
            b,
            pk,
            proof: None,
        }
    }
}


