//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "tokens")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "Text")]
    pub token_id: String,
    #[sea_orm(column_type = "Text")]
    pub token_name: String,
    #[sea_orm(column_type = "Text")]
    pub token_description: String,
    pub issuer_box: i64,
    pub issuance_box: i64,
    pub decimals: Option<i32>,
    pub minted: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
