[ergo_node]
url = "http://192.168.1.137:9053"
zmq_url = "tcp://192.168.1.137:9060"

[database]
user = "postgres"
password = "test"
host = "localhost"
port = 5432
db = "lagerg"

[chain_indexer]
tx_par = 10