[package]
name = "spectrum-insight"
version = "1.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
sqlx = { version = "0.7.1", features = ["runtime-tokio","postgres"] }
tokio = { version = "1", features = ["full"] }
